language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - python -m unittest tests/test_user_authentication.py
  - python -m unittest tests/test_bucketlist_item_operations.py
  - python -m unittest tests/test_bucketlist_operations.py
